services:
    simulator:
        build: .
        image: whse-test
        volumes:
            - .:/app
        command: [
            "--dataDir", "./data/9",
            "--router", "./build/router-linux-amd64",
            "--info"
        ]
